spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver      thymeleaf:    cache: falsesecurity:  oauth2:    client:      client-id: test
      client-secret: testScret  
server:  port: 80 
  
mybatis:  configuration:    map-underscore-to-camel-case: true  
    
